name: PHP Composer

# Trigger the workflow on push or pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
      # Check-out repository under GitHub workspace
      # https://github.com/actions/checkout
    - uses: actions/checkout@v2

    - name: Setup PHP
      # Action gives to setup the PHP environment to test application
      # https://github.com/shivammathur/setup-php
      uses: shivammathur/setup-php@v1
      with:
        # Specify the PHP version
        php-version: '7.4'

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: make install
  
    - name: Check CodeStyle
      run: make lint

    - name: Run PHPUnit tests
      run: make unit-test

      # Publish code coverage on Code Climate
      # https://docs.codeclimate.com/docs/github-actions-test-coverage
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: 422c66e010b5dc4f27651580166c456add7baf82fdfb82532ecfa3f756e7d231
      with:
        coverageCommand: test-phpunit
        debug: true
